use super::super::types::ParameterDescriptor;
use super::builders::{bool_descriptor, enum_descriptor, integer_descriptor, string_descriptor};

pub(super) fn routing_descriptors() -> Vec<ParameterDescriptor> {
    vec![
        string_descriptor(
            "routing.backend",
            "--backend",
            "Backend",
            "Runtime backend selection",
            "routing",
            Some("auto"),
        ),
        string_descriptor(
            "routing.accelerator",
            "--accelerator",
            "Accelerator",
            "Requested accelerator",
            "routing",
            Some("auto"),
        ),
        string_descriptor(
            "routing.device",
            "--device",
            "Device",
            "Device identifier",
            "routing",
            None,
        ),
        string_descriptor(
            "routing.precision",
            "--precision",
            "Precision",
            "Compute precision",
            "routing",
            Some("auto"),
        ),
        string_descriptor(
            "routing.quantization",
            "--quantization",
            "Quantization",
            "Weight quantization",
            "routing",
            Some("auto"),
        ),
        string_descriptor(
            "routing.profile",
            "--profile",
            "Profile",
            "Saved parameter profile",
            "routing",
            None,
        ),
        enum_descriptor(
            "routing.quality",
            "--quality",
            "Quality",
            "Quality profile",
            "routing",
            "balanced",
            &["draft", "balanced", "high", "maximum"],
        ),
        enum_descriptor(
            "routing.performance_preference",
            "--performance-preference",
            "Performance preference",
            "Planner optimization preference",
            "routing",
            "balanced",
            &[
                "quality",
                "balanced",
                "speed",
                "latency",
                "throughput",
                "memory",
            ],
        ),
        enum_descriptor(
            "routing.fallback_policy",
            "--fallback-policy",
            "Fallback policy",
            "Allowed backend fallback behavior",
            "routing",
            "backend",
            &["none", "backend", "degrade"],
        ),
        enum_descriptor(
            "routing.parameter_policy",
            "--parameter-policy",
            "Parameter policy",
            "Handling of unsupported explicit parameters",
            "routing",
            "strict",
            &["strict", "warn", "permissive"],
        ),
        bool_descriptor(
            "routing.allow_cpu_offload",
            "--allow-cpu-offload",
            "CPU offload",
            "Allow model components to be offloaded to host memory",
            "routing",
            true,
        ),
        bool_descriptor(
            "routing.allow_sequential_offload",
            "--allow-sequential-offload",
            "Sequential offload",
            "Allow sequential component offloading",
            "routing",
            false,
        ),
        bool_descriptor(
            "routing.allow_component_offload",
            "--allow-component-offload",
            "Component offload",
            "Allow selected components to be offloaded",
            "routing",
            true,
        ),
        bool_descriptor(
            "routing.allow_disk_offload",
            "--allow-disk-offload",
            "Disk offload",
            "Allow disk-backed model offloading",
            "routing",
            false,
        ),
        string_descriptor(
            "routing.attention_backend",
            "--attention-backend",
            "Attention backend",
            "Attention implementation",
            "routing",
            Some("auto"),
        ),
        bool_descriptor(
            "routing.compile",
            "--compile",
            "Compile",
            "Enable backend graph compilation",
            "routing",
            false,
        ),
        integer_descriptor(
            "routing.timeout",
            "--timeout",
            "Timeout",
            "Execution timeout in seconds",
            "routing",
            3600,
            1,
        ),
    ]
}
